apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mac-lab-db
  namespace: postgres
spec:
  instances: 1
  storage:
    size: 5Gi
  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: mac-lab-db-lb
              annotations:
                metallb.universe.tf/loadBalancerIPs: 172.19.255.201
            spec:
              type: LoadBalancer

  bootstrap:
    initdb:
      database: labdb
      owner: admin
      secret:
        name: postgres-admin-secret
